---
sidebar: sidebar 
permalink: rest-api/retrieve-keystone-data-with-digital-advisor-rest-api.html 
keywords: Keystone, Active IQ, Digital Advisor, APIs, programmatic interface 
summary: As APIs do Digital Advisor fornecem uma interface programática para buscar detalhes e métricas do serviço Keystone . 
---
= Comece a usar a API REST do Digital Advisor para recuperar dados do Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A API REST do Digital Advisor fornece uma interface programática para recuperar detalhes de assinatura e consumo do Keystone .

Em um nível alto, o fluxo de trabalho para interagir com a API REST do Digital Advisor envolve as seguintes etapas:

. Configure sua conta de Digital Advisor .  Você precisa ter credenciais válidas do site de suporte da NetApp para efetuar login no Digital Advisor.  Para saber mais, consulte https://docs.netapp.com/us-en/active-iq/task_login_activeiq.html["Faça login no Digital Advisor."]
. Entenda o processo de autenticação em duas etapas.
+
.. *Gerar um token de atualização*: Um token de atualização é obtido por meio do console do Digital Advisor usando credenciais do NetApp .  Este token é usado para garantir acesso contínuo sem a necessidade de logins repetidos.
.. *Gerar um token de acesso*: O token de atualização é usado para gerar tokens de acesso.  Um token de acesso é necessário para autorizar chamadas de API para o serviço Keystone e é válido por uma hora.


. Execute uma chamada de API para recuperar os dados desejados. Você pode recuperar programaticamente listas de clientes, dados de assinatura de clientes e detalhes de consumo de clientes.

