---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Keystone support, service request, support ticket 
summary: Se precisar de ajuda, entre em contato com a equipe de suporte do NetApp Keystone . 
---
= Obtenha ajuda com o Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A equipe de suporte do NetApp Keystone e o Keystone Success Manager (KSM) são responsáveis por fornecer serviços para suas assinaturas do Keystone .  Se precisar de ajuda, entre em contato com a equipe de suporte da Keystone .



== Suporte NetApp Keystone

A NetApp fornece serviços operacionais remotamente aos clientes da NetApp Keystone .  Esses serviços abrangem uma variedade de disciplinas operacionais em atividades de gerenciamento de armazenamento.  Esses serviços incluem gerenciamento de ativos e configuração, gerenciamento de capacidade e desempenho, gerenciamento de mudanças, gerenciamento de eventos, incidentes e problemas, atendimento de solicitações de serviço e relatórios.  A NetApp demonstra um estado de controle e evidências de suporte, conforme necessário.



== Informações adicionais

A NetApp usa a solução de monitoramento ITOM para monitorar proativamente e se conectar ao ambiente NetApp Keystone para solução de problemas.


NOTE: Em um modelo operado por parceiro, as solicitações de serviço do locatário e do sublocatário são atribuídas ao service desk do parceiro.  A ferramenta de suporte do parceiro pode ter integração com a solução ITOM.

Para mais informações sobre os serviços da Keystone , consulte:

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* Documentação do produto NetApphttps://docs.netapp.com["https://docs.netapp.com"^]




== Monitoramento de suporte Keystone

O suporte do NetApp Keystone monitora a integridade dos seus produtos e serviços assinados, fornece suporte remoto e colabora com seu gerente de sucesso do Keystone .

.Gerente de Sucesso Keystone
O Keystone Success Manager (KSM) trabalha em estreita colaboração com você em seus serviços Keystone e o atualiza sobre relatórios operacionais e de faturamento semanais ou mensais.  As responsabilidades são especificadas no seu contrato do NetApp Keystone .



== Gerando solicitações de serviço

Durante a integração, se você recebeu credenciais para acessar e usar o Netapp Keystone ServiceNow, você pode usar o portal para gerar solicitações de serviço para problemas relacionados às suas assinaturas do Keystone :

https://netappgssc.service-now.com/csm[]

Certifique-se de ter os detalhes do sistema, registros e informações relacionadas prontos antes de fazer a solicitação de serviço.  Quando você faz uma solicitação de serviço, a equipe de suporte da Keystone recebe o tíquete de suporte e acessa as informações para solução de problemas.  Você pode acompanhar seu tíquete do ServiceNow para saber o status e a resolução.

Para obter informações sobre como adicionar pacotes de suporte, consultelink:../installation/monitor-health.html["Gerar e coletar pacote de suporte"] .

Se você tiver um caso/tíquete aberto que precisa ser escalado, envie um e-mail para um dos seguintes endereços: keystone.services@netapp.com keystone.escalations@netapp.com
