---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: Saiba mais sobre o faturamento do Keystone para configurações específicas, incluindo volumes clonados, proteção avançada de dados e muito mais. 
---
= Cenários diversos para faturamento do Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Entender o faturamento do Keystone para configurações específicas pode ajudar você a otimizar o uso do serviço e gerenciar custos.  As configurações incluem volumes clonados, proteção avançada de dados, volumes temporários, políticas de QoS, destinos SnapMirror , LUNs e volumes de sistema/raiz.



== Faturamento de volumes clonados

Se os volumes forem clonados no ONTAP e você os usar para fazer backup e restaurar seus dados, poderá continuar usando os clones sem nenhum pagamento adicional.  No entanto, volumes clonados usados para qualquer outra finalidade em seu negócio por um período prolongado serão cobrados.

Observe o seguinte:

* Os volumes clones não são cobrados, desde que seu tamanho seja menor que 10% do volume pai (a capacidade física usada no volume clone em comparação com a capacidade física usada no volume pai).
* Não há período de carência de 24 horas para volumes clonados.  Somente o tamanho do clone é considerado.
* Quando o volume do clone excede 10% do tamanho físico do pai, o clone é cobrado como um volume padrão (capacidade lógica utilizada).




== Faturamento para proteção avançada de dados

A proteção avançada de dados usa o NetApp MetroCluster para espelhar dados entre dois clusters fisicamente separados.  Para agregados espelhados do MetroCluster , os dados são gravados duas vezes, uma vez em cada cluster.  O serviço Keystone cobra pelo consumo de cada lado de forma independente, resultando em dois registros de consumo idênticos.  As taxas adicionais são aplicadas a todas as capacidades da assinatura, independentemente de os dados estarem na origem ou se forem dados espelhados ou não espelhados.

Se você monitorar seus clusters por meio do ONTAP System Manager (Gerenciador do Sistema) ou do Active IQ Unified Manager (Gerenciador Unificado), poderá observar uma discrepância entre o consumo relatado nessas ferramentas e no Keystone.  O System Manager e o Unified Manager não relatam volumes no cluster espelhado (remoto) e, ao fazer isso, relatam metade das métricas de consumo que o serviço Keystone relata.

.Exemplo:
O Site A e o Site B são configurados em uma configuração MetroCluster .  Quando um usuário cria um volume de 10 TB no site A, um volume idêntico de 10 TB é criado no site B. O Keystone identifica 10 TB de consumo em cada site, para um aumento total de 20 TB.  O System Manager e o Unified Manager relatam um volume de 10 TB criado no site A, mas não relatam um volume de 10 TB no Site B.

Além disso, todos os volumes criados em um sistema Keystone com proteção avançada de dados serão contabilizados no consumo de proteção avançada de dados, independentemente de esses volumes serem espelhados ou não.



== Faturamento de volumes temporários

Ocasionalmente, volumes temporários (TMP) são criados pelo ONTAP ao mover volumes.  Esses volumes temporários têm vida curta e o consumo nesses volumes não é medido para faturamento.



== Políticas de faturamento e QoS adaptáveis

A Keystone mede o consumo com base nos níveis de serviço.  Cada nível de serviço está associado a uma política específica de qualidade de serviço adaptável (QoS).  Durante a implantação, você será informado dos detalhes de cada política de QoS adaptável para seus serviços Keystone assinados.  Durante as operações de gerenciamento de armazenamento, certifique-se de que seus volumes tenham as políticas de QoS adaptáveis apropriadas atribuídas de acordo com seus níveis de serviço assinados para evitar cobranças inesperadas.  Para obter mais informações sobre políticas de QoS adaptáveis no ONTAP, consultelink:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Garanta a taxa de transferência com visão geral de QoS"^] .



== Faturamento para destinos SnapMirror

O preço do volume de destino do SnapMirror é regido pela política de QoS adaptável para o nível de serviço atribuído na origem.  No entanto, se a origem não tiver uma política de QoS adaptável associada, o destino será cobrado com base no menor nível de serviço disponível.



== Faturamento de LUNs

Para LUNs, o mesmo padrão de cobrança é seguido para os volumes regidos por políticas de QoS adaptáveis.  Se políticas de QoS adaptáveis separadas forem definidas em LUNs, então:

* O tamanho do LUN é contado para consumo de acordo com o nível de serviço associado a esse LUN.
* O restante do espaço no volume, se houver, é cobrado de acordo com a política de QoS adaptável do nível de serviço definido no volume.




== Volumes de sistema e raiz

Os volumes do sistema e da raiz são monitorados como parte do monitoramento geral do serviço Keystone , mas não são contados nem cobrados.  O consumo nesses volumes é isento de faturamento.
