---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Saiba mais sobre os tipos de capacidades de armazenamento suportados pelo serviço NetApp Keystone STaaS para a versão 2. 
---
= Capacidades de armazenamento suportadas no Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O serviço NetApp Keystone STaaS suporta vários tipos de capacidades de armazenamento.  Entender esses diferentes termos de capacidade pode ajudar você a usar o Keystone.



[[logical-capacity]]
== Capacidade lógica

Estes são os dados colocados na infraestrutura Keystone por um cliente.  Todas as capacidades Keystone referem-se a uma capacidade lógica.  Por exemplo, se um arquivo de 1 TiB for armazenado na infraestrutura Keystone , um mínimo de 1 TiB de capacidade deverá ser adquirido.



[[committed-capacity]]
== Capacidade comprometida

Capacidade lógica mínima cobrada mensalmente durante a assinatura:

* A capacidade é comprometida com cada nível de serviço de desempenho.
* Capacidade comprometida e níveis de serviço adicionais podem ser adicionados durante o prazo.




[[changes-to-committed-capacity]]
=== Mudanças na capacidade comprometida

Durante o período de uma assinatura, você pode alterar as capacidades comprometidas.  No entanto, existem certas condições prévias:

* A capacidade comprometida pode ser diminuída com base em certas condições.  Para obter informações, consultelink:../concepts/capacity-requirements.html["Redução de capacidade"] .
* A capacidade comprometida não pode ser aumentada 90 dias antes do vencimento da sua assinatura, a menos que a assinatura seja renovada por um período adicional de 12 meses.
* Você pode solicitar alterações na capacidade contratada por meio do Console ou do seu Keystone Success Manager (KSM). Para obter informações sobre como solicitar alterações, consulte link:../concepts/support-services.html["Suporte NetApp Keystone"].




[[consumed-capacity]]
== Capacidade consumida

A capacidade consumida refere-se à capacidade (em TiB de storage) atualmente utilizada pelo serviço. Ela é calculada de forma diferente dependendo do tipo de storage de dados:

* *Armazenamento unificado ou otimizado para blocos*: A capacidade consumida é calculada com base no tipo de capacidade (lógica ou física) selecionado durante o processo de pedido. O cálculo é realizado por instância de nível de serviço de desempenho.
+
.. *Capacidade lógica*: É a soma de:
+
*** Capacidade lógica medida, antes das eficiências de dados do array de storage, para armazenar todas as instâncias e tipos de dados do cliente, como cópias, cópias espelhadas, versões e clones.
*** Capacidade física utilizada para armazenar metadados e dados diferenciais de snapshots e determinados clones.
*** Qualquer capacidade física provisionada de forma thick.


.. *Capacidade física*: É a soma de:
+
*** Capacidade física medida, após eficiências de dados do array de storage, para armazenar todas as instâncias e tipos de dados do cliente, como cópias, cópias espelhadas, versões e clones.
*** Capacidade física utilizada para armazenar metadados e dados diferenciais de snapshots.
*** Qualquer capacidade física provisionada de forma thick.




* *Armazenamento de objetos*: A capacidade consumida é calculada como a quantidade de capacidade física medida usada para armazenar todas as instâncias e tipos de dados do cliente em todos os nós. Esse cálculo é baseado nas políticas de gerenciamento do ciclo de vida das informações (ILM) configuradas.
* *Cloud Volumes ONTAP*: A capacidade consumida é calculada como a quantidade de capacidade lógica provisionada medida de todos os volumes do Cloud Volumes ONTAP.




[[burst-capacity]]
== Capacidade de ruptura

O serviço NetApp Keystone permite que você use capacidade adicional além da capacidade comprometida para um nível de serviço.  Isso é chamado de utilização da capacidade de pico.

Observe estes pontos:

* A capacidade de burst é acordada no acordo Keystone .  Geralmente, ele é definido como 20% acima da capacidade comprometida e é cobrado na mesma taxa da capacidade comprometida.
* A capacidade de burst pode ser consumida de forma elástica e é cobrada diariamente pela média consumida.




[[billed-capacity]]
== Capacidade faturada

Fatura mensal = (capacidade comprometida [TiB] * taxa comprometida [$/TiB]) + (capacidade de burst média diária provisionada [TiB] * taxa de burst [$/TiB]).  A fatura mensal contém uma cobrança mínima com base na capacidade comprometida.

A conta mensal varia além da cobrança mínima com base no consumo médio diário de capacidade de pico.
