---
sidebar: sidebar 
permalink: installation/install-itom-windows.html 
keywords: Windows installation Keystone, ITOM Collector installation 
summary: Instale o ITOM Collector em sistemas baseados em Windows. 
---
= Instalar o ITOM Collector em sistemas Windows
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Instale o ITOM Collector em um sistema Windows baixando o arquivo de configuração do ITOM Collector, executando o assistente InstallShield e inserindo as credenciais de monitoramento necessárias.


NOTE: A equipe de suporte da Keystone fornece um link dinâmico para baixar o arquivo de configuração do ITOM Collector, que expira em duas horas.

Você pode instalá-lo em sistemas Linux de acordo com suas necessidades.  Para instalar o ITOM Collector em sistemas Linux, consultelink:../installation/install-itom-linux.html["Instalar o ITOM Collector em sistemas Linux"] .

Siga estas etapas para instalar o software coletor ITOM no seu servidor Windows:

.Antes de começar
Certifique-se de que o serviço ITOM Collector tenha a permissão *Fazer logon como um serviço* em Política local/Atribuição de direitos de usuário nas configurações de política de segurança local do servidor Windows.

.Passos
. Baixe o arquivo de configuração do coletor ITOM para o seu servidor Windows.
. Abra o arquivo de instalação para iniciar o assistente do InstallShield.
. Aceite o contrato de licença de usuário final (EULA).  O assistente do InstallShield extrai os binários necessários e solicita que você insira as credenciais.
. Insira as credenciais da conta na qual o ITOM Collector será executado:
+
** Se o ITOM Collector não estiver monitorando outros servidores Windows, use o sistema local.
** Se o ITOM Collector estiver monitorando outros servidores Windows no mesmo domínio, use uma conta de domínio com permissões de administrador local.
** Se o ITOM Collector estiver monitorando outros servidores Windows que não fazem parte do mesmo domínio, use uma conta de administrador local e conecte-se a cada recurso com credenciais de administrador local.  Você pode optar por definir a senha para que ela não expire, para reduzir problemas de autenticação entre o ITOM Collector e seus recursos monitorados.


. Selecione o tamanho do coletor.  O padrão é o tamanho recomendado com base no arquivo de configuração.  Prossiga com o tamanho sugerido, a menos que tenha requisitos específicos.
. Selecione _Avançar_ para iniciar a instalação.  Você pode usar a pasta preenchida ou escolher uma diferente.  Uma caixa de status exibe o progresso da instalação, seguida pela caixa de diálogo Assistente do InstallShield concluído.


.O que vem a seguir?
Após a instalação bem-sucedida, entre em contato com a equipe de suporte do Keystone para validar a instalação bem-sucedida do ITOM Collector por meio do portal de suporte do ITOM.  Após a verificação, a equipe de suporte da Keystone configurará o ITOM Collector remotamente, incluindo mais descoberta de dispositivos e configuração de monitoramento, e enviará uma confirmação assim que a configuração estiver concluída.  Para dúvidas ou informações adicionais, entre em contato com keystone.services@netapp.com.
