---
sidebar: sidebar 
permalink: installation/install-itom-linux.html 
keywords: Linux installation, ITOM Collector installation 
summary: Instale o software ITOM Collector em sistemas baseados em Linux. 
---
= Instalar o ITOM Collector em sistemas Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Conclua algumas etapas para instalar o ITOM Collector, que coleta dados de métricas em seu ambiente de armazenamento.  Você pode instalá-lo em sistemas Windows ou Linux, dependendo de suas necessidades.


NOTE: A equipe de suporte da Keystone fornece um link dinâmico para baixar o arquivo de configuração do ITOM Collector, que expira em duas horas.

Para instalar o ITOM Collector em sistemas Windows, consultelink:../installation/install-itom-windows.html["Instalar o ITOM Collector em sistemas Windows"] .

Siga estas etapas para instalar o software no seu servidor Linux:

.Antes de começar
* Verifique se o Bourne shell está disponível para o script de instalação do Linux.
* Instalar o `vim-common` pacote para obter o binário *xxd* necessário para o arquivo de configuração do ITOM Collector.
* Garantir a `sudo package` é instalado se você planeja executar o ITOM Collector como um usuário não root.


.Passos
. Baixe o arquivo de configuração do coletor ITOM para o seu servidor Linux.
. Abra um terminal no servidor e execute o seguinte comando para alterar as permissões e tornar os binários executáveis:
`# chmod +x <installer_file_name>.bin`
. Execute o comando para iniciar o arquivo de configuração do coletor ITOM:
`#./<installer_file_name>.bin`
. A execução do arquivo de instalação solicita que você:
+
.. Aceite o contrato de licença de usuário final (EULA).
.. Insira os detalhes do usuário para a instalação.
.. Especifique o diretório pai da instalação.
.. Selecione o tamanho do coletor.
.. Forneça detalhes do proxy, se aplicável.
+
Para cada prompt, uma opção padrão é exibida.  É recomendável selecionar a opção padrão, a menos que você tenha requisitos específicos.  Pressione a tecla *Enter* para escolher a opção padrão.  Quando a instalação for concluída, uma mensagem confirmará que o ITOM Collector foi instalado com sucesso.





[NOTE]
====
* O arquivo de configuração do coletor ITOM faz adições a `/etc/sudoers` para lidar com reinicializações de serviço e despejos de memória.
* A instalação do ITOM Collector no servidor Linux cria um usuário padrão chamado *ITOM* para executar o ITOM Collector sem privilégios de root.  Você pode escolher um usuário diferente ou executá-lo como root, mas é recomendável usar o usuário ITOM criado pelo script de instalação do Linux.


====
.O que vem a seguir?
Após a instalação bem-sucedida, entre em contato com a equipe de suporte do Keystone para validar a instalação bem-sucedida do ITOM Collector por meio do portal de suporte do ITOM.  Após a verificação, a equipe de suporte da Keystone configurará o ITOM Collector remotamente, incluindo mais descoberta de dispositivos e configuração de monitoramento, e enviará uma confirmação assim que a configuração estiver concluída.  Para dúvidas ou informações adicionais, entre em contato com keystone.services@netapp.com.
