---
sidebar: sidebar 
permalink: installation/vapp-prereqs.html 
keywords: prerequisites, VMware vSphere, vApp 
summary: Seu sistema VMware vSphere deve atender a vários requisitos antes que você possa instalar o Keystone Collector. 
---
= Requisitos de infraestrutura virtual
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Seu sistema VMware vSphere deve atender a vários requisitos antes que você possa instalar o Keystone Collector.

.Pré-requisitos para a VM do servidor Keystone Collector:
* Sistema operacional: servidor VMware vCenter e ESXi 8.0 ou posterior
* Núcleo: 1 CPU
* RAM: 2 GB de RAM
* Espaço em disco: 20 GB vDisk




== Outros requisitos

Certifique-se de que os seguintes requisitos genéricos sejam atendidos:



=== Requisitos de rede

Os requisitos de rede do Keystone Collector estão listados na tabela a seguir.


NOTE: O Keystone Collector requer conectividade com a internet.  Você pode fornecer conectividade à Internet por roteamento direto através do Gateway padrão (via NAT) ou através do Proxy HTTP.  Ambas as variantes são descritas aqui.

|===


| Fonte | Destino | Serviço | Protocolo e Portas | Categoria | Propósito 


 a| 
Colecionador Keystone (para Keystone ONTAP)
 a| 
Active IQ Unified Manager (Gerenciador unificado)
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obrigatório (se estiver usando Keystone ONTAP)
 a| 
Coleta de métricas de uso do Keystone Collector para ONTAP



 a| 
Coletor Keystone (para Keystone StorageGRID)
 a| 
Nós de administração do StorageGRID
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obrigatório (se estiver usando Keystone StorageGRID)
 a| 
Coleta de métricas de uso do Keystone Collector para StorageGRID



 a| 
Keystone Collector (genérico)
 a| 
Internet (conforme requisitos de URL fornecidos posteriormente)
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obrigatório (conectividade à internet)
 a| 
Software Keystone Collector, atualizações do sistema operacional e upload de métricas



 a| 
Keystone Collector (genérico)
 a| 
Proxy HTTP do cliente
 a| 
Proxy HTTP
 a| 
Porta de proxy do cliente
 a| 
Obrigatório (conectividade à internet)
 a| 
Software Keystone Collector, atualizações do sistema operacional e upload de métricas



 a| 
Keystone Collector (genérico)
 a| 
Servidores DNS do cliente
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
Obrigatório
 a| 
Resolução de DNS



 a| 
Keystone Collector (genérico)
 a| 
Servidores NTP do cliente
 a| 
NTP
 a| 
UDP 123
 a| 
Obrigatório
 a| 
Sincronização de tempo



 a| 
Colecionador Keystone (para Keystone ONTAP)
 a| 
Gerente Unificado
 a| 
MYSQL
 a| 
TCP 3306
 a| 
Funcionalidade opcional
 a| 
Coleta de métricas de desempenho para Keystone Collector



 a| 
Keystone Collector (genérico)
 a| 
Sistema de Monitoramento de Clientes
 a| 
HTTPS
 a| 
TCP 7777
 a| 
Funcionalidade opcional
 a| 
Relatório de saúde do Keystone Collector



 a| 
Estações de trabalho de operações do cliente
 a| 
Colecionador de Keystone
 a| 
SSH
 a| 
TCP 22
 a| 
Gerenciamento
 a| 
Acesso ao Gerenciamento do Coletor Keystone



 a| 
Endereços de gerenciamento de cluster e nó do NetApp ONTAP
 a| 
Colecionador de Keystone
 a| 
HTTP_8000, PING
 a| 
TCP 8000, solicitação/resposta de eco ICMP
 a| 
Funcionalidade opcional
 a| 
Servidor web para atualizações de firmware ONTAP

|===

NOTE: A porta padrão do MySQL, 3306, é restrita apenas ao host local durante uma nova instalação do Unified Manager, o que impede a coleta de métricas de desempenho para o Keystone Collector. Para obter mais informações, consulte link:addl-req.html["Requisitos do ONTAP"] .



=== Acesso URL

O Keystone Collector precisa de acesso aos seguintes hosts da Internet:

|===


| Endereço | Razão 


 a| 
https://keystone.netapp.com[]
 a| 
Atualizações do software Keystone Collector e relatórios de uso



 a| 
https://support.netapp.com[]
 a| 
NetApp HQ para informações de cobrança e entrega de AutoSupport

|===