---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: Problemas encontrados em versões anteriores dos serviços NetApp Keystone STaaS foram corrigidos em versões posteriores. 
---
= Problemas corrigidos no Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Problemas encontrados em versões anteriores dos serviços NetApp Keystone STaaS foram corrigidos em versões posteriores.

[cols="3*"]
|===
| Descrição do problema | Depois da correção | Corrigido na versão 


 a| 
Linha de limite de pico ausente nos gráficos de tendência de consumo para assinaturas configuradas com uma configuração MetroCluster no painel do Digital Advisor , mostrando um status incorreto *Acima do limite de pico*.
 a| 
Fixo
 a| 
2025-08-28



 a| 
Na aba *Ativos*, os ativos do StorageGRID não são visíveis.
 a| 
Fixo
 a| 
2025-06-19



 a| 
Para o nível de serviço Advance Data-Protect, na guia *Tendência de consumo*, o gráfico mostra uma divisão para sites primários e espelhos.
 a| 
O gráfico não mostra mais uma divisão entre sites primários e espelhos.
 a| 
2025-06-19



 a| 
Quando o Keystone Collector existente instalado usando um pacote Debian tenta configurar um Proxy HTTP ou habilitar o Unified Manager por meio do TUI de gerenciamento do Keystone Collector, o TUI deixa de responder.
 a| 
Fixo
 a| 
2025-05-19



 a| 
O Keystone Collector for StorageGRID não é configurado corretamente devido à ausência de configurações comuns.
 a| 
Fixo
 a| 
2025-05-12



 a| 
O Keystone Collector não consegue coletar dados de uso para clusters ONTAP executando versões anteriores à 9.11.
 a| 
Fixo
 a| 
2025-04-30



 a| 
Os valores de consumo para assinaturas vinculadas mostram números negativos incorretos, fazendo com que o uso total comprometido seja exibido incorretamente alto.
 a| 
Fixo
 a| 
2025-04-14



 a| 
Não é possível visualizar dados históricos na aba *Tendência de consumo* para níveis de serviço de algumas assinaturas.
 a| 
Fixo
 a| 
2025-04-14



 a| 
Falta a opção *Assinaturas Keystone * na *Lista de Observação* e a opção *Número da Assinatura* nos *Relatórios* no painel do Digital Advisor .
 a| 
Fixo
 a| 
2025-03-19



 a| 
Faltam algumas assinaturas do Keystone na *Lista de observação* após criar ou modificar a lista de observação no painel do Digital Advisor .
 a| 
Fixo
 a| 
2025-03-19



 a| 
Não é possível visualizar dados históricos na aba *Tendência de consumo* para níveis de serviço associados a uma assinatura que expirou e foi renovada com o mesmo ID de rastreamento, mas com níveis de serviço diferentes.
 a| 
Fixo
 a| 
2025-03-19



 a| 
Não é possível gerar relatórios para assinaturas ao selecionar mais de 10 a 12 assinaturas na guia *Assinaturas* na página *Assinaturas Keystone *.
 a| 
Fixo
 a| 
2025-01-08



 a| 
A subguia *Resumo do Volume* na guia *Volumes e Objetos* não carrega para assinaturas do StorageGrid.
 a| 
Fixo
 a| 
2024-11-21



 a| 
O campo *Data inicial* para selecionar o intervalo de datas exibe uma data futura por padrão ao navegar até a guia *Tendência de consumo*.
 a| 
Fixo
 a| 
2024-09-04



 a| 
O TUI de gerenciamento do Keystone Collector deixa de responder ao configurar políticas de AQoS.
 a| 
Fixo
 a| 
2024-08-07



 a| 
Os gráficos de uso exibem dados além do período de um único dia especificado quando a data correspondente ao dia atual é selecionada como data de início e término do mês anterior na opção *Tendência de capacidade* na guia *Tendências de capacidade*.
 a| 
Os gráficos de uso agora exibem corretamente os dados para o período de um único dia especificado.
 a| 
2024-06-27



 a| 
Os dados históricos acumulados de pico não estão disponíveis para os níveis de serviço *CVO Primário* e *CVO Secundário* na guia *Tendência de Capacidade* para assinaturas que não estão configuradas com uma configuração MetroCluster .
 a| 
Fixo
 a| 
2024-06-21



 a| 
Exibição incorreta do valor consumido do armazenamento de objetos listado na guia *Detalhes do volume* para assinaturas do AutoSupport .
 a| 
O valor consumido para armazenamento de objetos agora é exibido corretamente.
 a| 
2024-06-21



 a| 
Não é possível visualizar informações em nível de cluster na guia *Ativos* para assinaturas do AutoSupport configuradas com uma configuração MetroCluster .
 a| 
Fixo
 a| 
21 de junho de 2024



 a| 
Deslocamento de dados Keystone em relatórios CSV se a coluna *Nome da conta* em relatórios CSV, gerados na guia *Tendência de capacidade*, incluir um nome de conta com uma vírgula `(,)` .
 a| 
Os dados do Keystone estão alinhados corretamente nos relatórios CSV.
 a| 
2024-05-29



 a| 
Exiba o uso acumulado de pico na guia *Tendência de capacidade* mesmo se o consumo estiver abaixo da capacidade comprometida.
 a| 
Fixo
 a| 
2024-05-29



 a| 
Texto de dica de ferramenta incorreto para o ícone de índice *Current Burst* na guia *Capacity Trend*.
 a| 
Exibe o texto correto da dica de ferramenta "_A quantidade de capacidade de burst que está sendo consumida no momento.  Observe que isso se refere ao período de cobrança atual, não ao intervalo de datas selecionado._"
 a| 
2024-03-28



 a| 
Informações sobre volumes não compatíveis com AQoS e parceiros do MetroCluster não estarão disponíveis para assinaturas do AutoSupport se os dados do Keystone não estiverem presentes por 24 horas.
 a| 
Fixo
 a| 
2024-03-28



 a| 
Incompatibilidade ocasional no número de volumes não compatíveis com AQoS listados nas guias *Resumo do volume* e *Detalhes do volume* se houver dois níveis de serviço atribuídos a um volume que atenda à conformidade com AQoS para apenas um nível de serviço.
 a| 
Fixo
 a| 
2024-03-28



 a| 
Não há informações disponíveis na aba *Ativos* para assinaturas do AutoSupport .
 a| 
Fixo
 a| 
2024-03-14



 a| 
Se o MetroCluster e o FabricPool fossem habilitados em um ambiente onde os planos de tarifas para armazenamento em camadas e de objetos fossem aplicáveis, os níveis de serviço poderiam ser derivados incorretamente para os volumes espelhados (volumes constituintes e do FabricPool ).
 a| 
Níveis de serviço corretos são aplicados aos volumes espelhados.
 a| 
2024-02-29



 a| 
Para algumas assinaturas com um único nível de serviço ou plano de tarifas, a coluna de conformidade com AQoS estava ausente na saída CSV dos relatórios da guia *Volumes*.
 a| 
A coluna de conformidade fica visível nos relatórios.
 a| 
2024-02-29



 a| 
Em alguns ambientes MetroCluster , anomalias ocasionais foram detectadas nos gráficos de densidade de IOPS na guia *Desempenho*.  Isso aconteceu devido ao mapeamento impreciso de volumes para níveis de serviço.
 a| 
Os gráficos são exibidos corretamente.
 a| 
2024-02-29



 a| 
O indicador de uso para um recorde de consumo explosivo estava sendo exibido em âmbar.
 a| 
O indicador aparece em vermelho.
 a| 
2023-12-13



 a| 
O intervalo de datas e os dados nas guias Tendência de capacidade, Uso atual e Desempenho não foram convertidos para o fuso horário UTC.
 a| 
O intervalo de datas da consulta e os dados em todas as guias são exibidos no horário UTC (fuso horário do servidor).  O fuso horário UTC também é exibido em cada campo de data nas guias.
 a| 
2023-12-13



 a| 
Houve uma incompatibilidade na data de início e na data de término entre as guias e os relatórios CSV baixados.
 a| 
Fixo.
 a| 
2023-12-13

|===